### PR TITLE
Updated distance matrix code

### PR DESCRIPTION
**Pull request by autermann**
The distance matrix code now works with the newly created classes.

```r
demo("distance-matrix", package = "sensorweb4R")
```

### CODE REVIEW

**Comment by nuest** [comment]
Nice!
Documentation needs to be slightly fixed: Try `?nearestStations` > the argument `x` is described to times, and differently. Can you integrate that into one sentence: for "distance" this means..., for "distanceMatrix" this means...

**Comment by autermann** [comment]
Yeah... that's not the only example for this. I'm not yet accustomed to the R documentation style. I've felt that grouping some functions together would be a good idea, but it doesn't make life easier... Especially when using `roxygen2`. E.g. I can put a function into the `Rd` of a class, but it won't work for generics. Also, I've not yet figured out how to describe the generic version of a function and an actual implementation (sometimes with additional parameters) in the same `Rd` (see ``?`accessor-methods` `` or ``?`query-methods` ``)

btw.: currently, `roxygen2::roxygenize()` fails with an strange error, while `devtools::check()` (which does the same thing + more) works...

**Comment by nuest** [comment]
Yes, it does make sense to group, and I liked that about the help pages. The help must not be long, we focus on the vignette for documentation. Grouping is probably easier if we would edit the rd files by hand, but I still think we should stay with roxygen. 

Suggestion: It is ok if `x` is listed more than once, just make the descriptions clear to distinguish the differenct cases.

Regarding roxygenize - let's not worry about it, put it in the developer README to build the documentation with `devtools`.

**Comment by autermann** [comment]
@nuest have a look...

**Pull request merged**
